### ISSUE TITLE
Support for FFT Shifts | `fftshifted` & `ifftshifted`

### ISSUE THREAD

**Issue by roflmaostc** [JuliaArrays/ShiftedArrays.jl#43]
Hey,

is there any possibility that we can include something like a `ShiftedArray.fftshift` or `ShiftedArray.ifftshift`.
It would be a convenient wrapper to call `fftshift` and `ifftshift` but prevent the allocation of memory.

There might be some performance issues when accidentally providing a `ShiftedArrray` to a `fft` but I'm not sure and we might discuss such issues?

If you support that idea we can help adding that :)

Thanks,

Felix

**Comment by piever** [comment]
Hey, it looks like it would be dependency-free to add it, so a PR is definitely welcome.

>There might be some performance issues when accidentally providing a `ShiftedArrray `to a `fft` but I'm not sure and we might discuss such issues?

In the end AFAIU `fft` is done by a C library, so I think the `CircShiftedArray` will have to be converted to a standard layout, and then the same C routine would be called.

**Comment by roflmaostc** [comment]
OK cool 😎
I'll prepare a PR for that!

**Comment by roflmaostc** [comment]
Thanks a lot for your help and sorry for the slight mess :upside_down_face:
