### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by mkitti** [JuliaArrays/ShiftedArrays.jl#54]
Recent changes to the package look particular attractive. Would it be possible to make a release?

**Comment by piever** [comment]
Yes, a release is long overdue... As it will be breaking (i.e., 2.0), we still need to finalize a decision on https://github.com/JuliaArrays/ShiftedArrays.jl/pull/37#issuecomment-1083089037 (unexporting `lag` and `lead`).
